### ISSUE TITLE
Link back to the-o and LangLang

### ISSUE THREAD

**Issue by KazZBodnar** [KazMalhotra/dino#2]
# Link Back Please'
The kazmal.tech/dino doesn't have any kind of link back to the-o.tech and langlang.tech, both of which have links to the stupid dinosaur jokes. Please add them.

**Comment by KazMalhotra** [comment]
I merged your pull request linking to langlang.tech and the-o.tech. However, there still is an issue. The the-o.tech link is broken. Please fix this in a PR.
Thanks,
Kaz
